version: "3"
services:
  app:
    container_name: containerize_app_1
    # your code goes here ...
    build:
      context: ./app
    ports:
      - "8000"
  nginx:
    container_name: containerize_nginx_1
    # your code goes here ...
    build:
      context: ./nginx        
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/files:/etc/nginx/certs
