version: "3"
services:
  app:
    container_name: containerize_app_1
    # your code goes here ...
    build:
      context: ./app
    ports:
      - "5000:5000"
  nginx:
    container_name: containerize_nginx_1
    # your code goes here ...
    build:
      context: ./nginx        
    ports:
      - "443:443"
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/files/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/files/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - app