version: '3'

services:
  web:
    image: your-python-app-image:latest
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/files:/etc/nginx/files:ro
    depends_on:
      - web
    restart: always
